import { ArrowLeft, Film, FolderOpen, LoaderCircle } from "lucide-react";
import { useLocation, useRoute } from "wouter";
import { MemberHeader } from "@/components/MemberHeader";
import { ProMovieGuard, useProMovieMember } from "@/components/ProMovieGuard";
import { trpc } from "@/lib/trpc";

function CategoryView() {
  const [, params] = useRoute("/category/:id"); const [, setLocation] = useLocation(); const { token, data: member } = useProMovieMember(); const categoryId = Number(params?.id); const query = trpc.promovie.category.useQuery({ token, categoryId }, { enabled: Boolean(token) && Number.isFinite(categoryId) });
  if (!member || query.isLoading) return <div className="grid min-h-screen place-items-center bg-[#0A0A0A]"><LoaderCircle className="h-7 w-7 animate-spin text-[#E50914]" /></div>;
  if (!query.data) return <div className="grid min-h-screen place-items-center bg-[#0A0A0A]"><button onClick={() => setLocation("/")} className="secondary-action">Return home</button></div>;
  const { category, movies } = query.data;
  return <div className="min-h-screen bg-[#0A0A0A] text-white"><MemberHeader member={member} /><main className="container py-7"><button onClick={() => setLocation("/")} className="mb-6 inline-flex items-center gap-2 text-sm font-bold text-zinc-400 hover:text-white"><ArrowLeft className="h-4 w-4" />All categories</button><section className="relative isolate min-h-[280px] overflow-hidden rounded-[1.7rem] border border-white/[.08] bg-zinc-900">{category.coverUrl && <img src={category.coverUrl} alt="" className="absolute inset-0 h-full w-full object-cover opacity-70" />}<div className="absolute inset-0 bg-gradient-to-r from-black via-black/70 to-black/15" /><div className="relative flex min-h-[280px] max-w-xl flex-col justify-end p-7 sm:p-10"><p className="text-xs font-bold uppercase tracking-[.18em] text-red-300">Category folder</p><h1 className="mt-3 font-display text-6xl tracking-[-.06em]">{category.name}</h1><p className="mt-3 text-sm leading-6 text-zinc-300">Choose a real title to open its movie or episode folder.</p></div></section><section className="mt-10"><div className="mb-5 flex items-center justify-between"><h2 className="font-display text-4xl tracking-[-.05em]">Titles</h2><span className="text-sm text-zinc-500">{movies.length} title{movies.length === 1 ? "" : "s"}</span></div>{movies.length === 0 ? <div className="rounded-[1.5rem] border border-white/[.08] bg-zinc-950 p-8 text-sm leading-6 text-zinc-500"><FolderOpen className="mb-4 h-6 w-6 text-[#E50914]" />This category is ready, but no published movie folders exist yet.</div> : <div className="grid gap-5 grid-cols-2 md:grid-cols-3 xl:grid-cols-5">{movies.map(movie => <button key={movie.id} onClick={() => setLocation(`/movie/${movie.id}`)} className="group text-left"><div className="aspect-[2/3] overflow-hidden rounded-2xl border border-white/10 bg-zinc-900">{movie.posterUrl || movie.thumbnailUrl ? <img src={movie.posterUrl || movie.thumbnailUrl || ""} alt={`${movie.title} poster`} className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /> : <div className="grid h-full place-items-center bg-[radial-gradient(circle_at_70%_20%,rgba(229,9,20,.28),transparent_32%),#191919]"><Film className="h-8 w-8 text-zinc-600" /></div>}</div><p className="mt-3 font-bold text-white">{movie.title}</p><p className="mt-1 text-xs text-zinc-500">{movie.contentType === "series" ? "Series folder" : "Movie folder"} · {movie.releaseYear}</p></button>)}</div>}</section></main></div>;
}
export default function Category() { return <ProMovieGuard><CategoryView /></ProMovieGuard>; }
