import { Activity, ArrowRight, CalendarDays, ChevronRight, CircleDot, LoaderCircle, MapPin, RefreshCw, Trophy } from "lucide-react";
import { MemberHeader } from "@/components/MemberHeader";
import { ProMovieGuard, useProMovieMember } from "@/components/ProMovieGuard";
import { trpc } from "@/lib/trpc";

const formatUpdated = (value?: string) => {
  if (!value) return "Waiting for first update";
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? "Updated just now" : `Updated ${date.toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })}`;
};

function ScoreLine({ team, score, active }: { team: string; score?: { runs: number | null; wickets: number | null; overs: string | null }; active?: boolean }) {
  return <div className="flex items-center justify-between gap-3 py-3"><div className="flex min-w-0 items-center gap-3"><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-full text-xs font-black ${active ? "bg-[#E50914] text-white" : "bg-white/[.06] text-zinc-400"}`}>{team.slice(0, 2).toUpperCase()}</span><span className="truncate text-sm font-bold text-white">{team}</span></div>{score && <div className="text-right"><p className="font-display text-2xl tracking-[-.04em] text-white">{score.runs === null ? "—" : score.runs}/{score.wickets === null ? "—" : score.wickets}</p>{score.overs && <p className="text-[10px] font-bold uppercase tracking-[.12em] text-zinc-500">{score.overs} overs</p>}</div>}</div>;
}

function CricketHubView() {
  const { token, data: member } = useProMovieMember();
  const live = trpc.promovie.cricket.liveMatches.useQuery({ token }, { enabled: Boolean(token), refetchInterval: 30_000, refetchIntervalInBackground: true });
  if (!member) return <div className="grid min-h-screen place-items-center bg-[#0A0A0A]"><LoaderCircle className="h-7 w-7 animate-spin text-[#E50914]" /></div>;
  const matches = live.data?.matches || [];

  return <div className="min-h-screen bg-[#0A0A0A] text-white">
    <MemberHeader member={member} />
    <main className="container pb-14">
      <section className="relative mt-6 overflow-hidden rounded-[1.8rem] border border-white/[.08] bg-gradient-to-br from-[#2a070b] via-[#140b0e] to-zinc-950 px-5 py-8 sm:mt-8 sm:px-9 sm:py-11"><div className="pointer-events-none absolute -right-16 -top-24 h-64 w-64 rounded-full bg-[#E50914]/20 blur-3xl" /><div className="relative flex flex-col justify-between gap-7 md:flex-row md:items-end"><div><p className="flex items-center gap-2 text-xs font-black uppercase tracking-[.2em] text-[#ff6670]"><CircleDot className="h-3.5 w-3.5 animate-pulse" />Live cricket centre</p><h1 className="mt-3 max-w-2xl font-display text-6xl leading-[.95] tracking-[-.06em] sm:text-7xl">Scoreboard<br /><span className="text-white/55">without the noise.</span></h1><p className="mt-5 max-w-xl text-sm leading-6 text-zinc-400">Live match scores, innings progress, and match status in one fast, mobile-first hub.</p></div><div className="flex shrink-0 items-center gap-2 rounded-full border border-white/10 bg-black/30 px-3 py-2 text-xs font-bold text-zinc-300 backdrop-blur"><span className="h-2 w-2 animate-pulse rounded-full bg-[#E50914]" />{formatUpdated(live.data?.fetchedAt)}<button aria-label="Refresh live scores" onClick={() => void live.refetch()} className="ml-1 rounded-full p-1.5 text-zinc-400 transition hover:bg-white/10 hover:text-white"><RefreshCw className={`h-3.5 w-3.5 ${live.isFetching ? "animate-spin" : ""}`} /></button></div></div></section>
      <section className="mt-7 flex items-center justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#E50914]">Live matches</p><h2 className="mt-1 font-display text-4xl tracking-[-.05em]">Now on the field</h2></div><div className="hidden items-center gap-2 text-xs font-bold text-zinc-500 sm:flex"><Activity className="h-4 w-4 text-[#E50914]" />Auto-refreshes every 30 seconds</div></section>
      {live.isLoading ? <div className="mt-5 grid place-items-center rounded-[1.5rem] border border-white/[.08] bg-zinc-950 py-20"><LoaderCircle className="h-8 w-8 animate-spin text-[#E50914]" /><p className="mt-4 text-sm text-zinc-500">Loading live scorecards…</p></div> : !live.data?.available ? <div className="mt-5 rounded-[1.5rem] border border-amber-300/20 bg-amber-300/[.05] p-7"><Trophy className="h-7 w-7 text-amber-200" /><h3 className="mt-5 font-display text-3xl">Live data is almost ready</h3><p className="mt-2 max-w-xl text-sm leading-6 text-zinc-400">{live.data?.message || "The live-score provider is temporarily unavailable."} Add the key to your server environment, then Cricket Hub will update automatically without changing the UI.</p></div> : matches.length === 0 ? <div className="mt-5 rounded-[1.5rem] border border-white/[.08] bg-zinc-950 p-8"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-[#E50914]/10 text-[#ff5963]"><CalendarDays className="h-6 w-6" /></div><h3 className="mt-5 font-display text-3xl">No live matches right now</h3><p className="mt-2 max-w-lg text-sm leading-6 text-zinc-500">Cricket Hub is connected and will check again automatically when a match goes live.</p></div> : <div className="mt-5 grid gap-4 lg:grid-cols-2">{matches.map((match, index) => { const teams = match.teams.length ? match.teams : match.innings.map(innings => innings.team); const scores = match.innings; return <article key={match.id || index} className="overflow-hidden rounded-[1.5rem] border border-white/[.08] bg-zinc-950 transition hover:border-white/20"><div className="flex items-start justify-between gap-4 border-b border-white/[.07] bg-white/[.025] px-5 py-4"><div><div className="flex flex-wrap items-center gap-2"><span className="inline-flex items-center gap-1.5 rounded-full bg-[#E50914]/12 px-2.5 py-1 text-[10px] font-black uppercase tracking-[.12em] text-[#ff6670]"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-[#E50914]" />Live</span><span className="text-[10px] font-black uppercase tracking-[.14em] text-zinc-600">{match.matchType}</span></div><h3 className="mt-3 max-w-md text-sm font-bold leading-5 text-white">{match.name}</h3></div><ChevronRight className="mt-2 h-4 w-4 shrink-0 text-zinc-600" /></div><div className="px-5"><ScoreLine team={teams[0] || "Team 1"} score={scores[0]} active /><ScoreLine team={teams[1] || "Team 2"} score={scores[1]} /><p className="border-t border-white/[.07] py-3 text-xs font-semibold text-[#ffcf55]">{match.status}</p></div><div className="flex flex-wrap gap-4 border-t border-white/[.07] px-5 py-3 text-[10px] font-bold uppercase tracking-[.12em] text-zinc-600"><span className="inline-flex items-center gap-1.5"><MapPin className="h-3 w-3" />{match.venue}</span>{match.dateTimeGMT && <span>{new Date(match.dateTimeGMT).toLocaleDateString()}</span>}</div></article>; })}</div>}
      <div className="mt-8 rounded-[1.5rem] border border-white/[.08] bg-zinc-950 p-5 text-sm text-zinc-500 sm:flex sm:items-center sm:justify-between"><span>Want to watch something after the final over?</span><button onClick={() => window.location.assign("/movies")} className="mt-3 inline-flex items-center gap-2 font-bold text-white transition hover:text-[#ff5963] sm:mt-0">Browse ProMovie <ArrowRight className="h-4 w-4" /></button></div>
    </main>
  </div>;
}

export default function CricketHub() { return <ProMovieGuard><CricketHubView /></ProMovieGuard>; }
