import { CalendarDays, CircleUserRound, Download, Film, History, Mail, Phone, WalletCards } from "lucide-react";
import { MemberHeader } from "@/components/MemberHeader";
import { ProMovieGuard, useProMovieMember } from "@/components/ProMovieGuard";
import { trpc } from "@/lib/trpc";

function ProfileView() {
  const { token, data: member } = useProMovieMember();
  const profile = trpc.promovie.profile.useQuery({ token }, { enabled: Boolean(token) });
  if (!member) return null;
  const details = profile.data?.profile ?? member;
  return <div className="min-h-screen bg-[#0A0A0A] text-white"><MemberHeader member={member} /><main className="container py-10 sm:py-14"><div className="grid gap-6 lg:grid-cols-[1.05fr_.95fr]"><section className="rounded-[1.7rem] border border-white/[.09] bg-zinc-950 p-6 sm:p-8"><div className="flex flex-col gap-6 sm:flex-row sm:items-center"><div className="grid h-20 w-20 place-items-center rounded-3xl bg-zinc-800 text-zinc-300"><CircleUserRound className="h-10 w-10" /></div><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#E50914]">Member profile</p><h1 className="mt-2 font-display text-5xl tracking-[-.06em]">{details.name || "ProMovie member"}</h1><p className="mt-2 text-sm text-zinc-500">Joined {new Date(details.createdAt).toLocaleDateString()}</p></div></div><div className="mt-8 grid gap-3 border-t border-white/[.07] pt-6"><div className="profile-line"><Mail className="h-4 w-4" /><span>{details.email || "No Gmail recorded"}</span></div><div className="profile-line"><Phone className="h-4 w-4" /><span>{details.mobile || "No mobile recorded"}</span></div><div className="profile-line"><CalendarDays className="h-4 w-4" /><span>Member since {new Date(details.createdAt).toLocaleDateString()}</span></div></div></section><section className="relative overflow-hidden rounded-[1.7rem] border border-[#FFC107]/20 bg-gradient-to-br from-[#2c2102] via-[#171102] to-zinc-950 p-6 sm:p-8"><div className="absolute -right-9 -top-8 h-40 w-40 rounded-full bg-[#FFC107]/10 blur-2xl" /><WalletCards className="relative h-7 w-7 text-[#FFC107]" /><p className="relative mt-8 text-sm font-bold uppercase tracking-[.18em] text-[#ffda6b]">Wallet balance</p><p className="relative mt-2 font-display text-7xl tracking-[-.07em] text-[#FFC107]">{details.coinBalance.toLocaleString()}</p><p className="relative mt-1 text-sm text-[#f4d77a]/70">Coins available for real uploaded titles.</p><div className="relative mt-8 flex items-center gap-3 text-xs leading-5 text-[#f6dfa0]/80"><span className="grid h-8 w-8 place-items-center rounded-full border border-[#FFC107]/20"><Film className="h-4 w-4" /></span>Watch active playback to earn 50 coins per verified minute.</div></section></div>
  <section className="mt-10 grid gap-6 xl:grid-cols-2"><HistoryCard title="Transaction history" icon={<History className="h-5 w-5" />} empty="No coin activity yet. Watching or downloading a real title will appear here." count={profile.data?.transactions.length ?? 0} /><HistoryCard title="Watch history" icon={<Film className="h-5 w-5" />} empty="No watched episodes yet. Your active viewing progress will appear here." count={profile.data?.watches.length ?? 0} /><HistoryCard title="My downloads" icon={<Download className="h-5 w-5" />} empty="No downloads yet. Earn coins by watching, then unlock real uploads here." count={profile.data?.downloads.length ?? 0} /></section></main></div>;
}
function HistoryCard({ title, icon, empty, count }: { title: string; icon: React.ReactNode; empty: string; count: number }) { return <section className="rounded-[1.5rem] border border-white/[.08] bg-zinc-950 p-6"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-white/[.05] text-zinc-300">{icon}</span><h2 className="font-display text-3xl tracking-[-.05em]">{title}</h2></div><div className="mt-6 border-t border-dashed border-white/10 pt-6 text-sm leading-6 text-zinc-500">{count === 0 ? empty : `${count} record${count === 1 ? "" : "s"} available in your account history.`}</div></section>; }
export default function Profile() { return <ProMovieGuard><ProfileView /></ProMovieGuard>; }
