import { Expand, Gauge, Pause, Play, RotateCcw, RotateCw, Settings2, Sun, Volume2 } from "lucide-react";
import { PointerEvent, useEffect, useMemo, useRef, useState } from "react";

const speeds = [0.25, 0.5, 0.75, 1, 1.25, 1.5, 2, 3, 4];
const qualityChoices = ["Auto", "144p", "240p", "360p", "480p", "720p HD", "1080p HD"];

type BroPlayerProps = { source: string; title: string; poster?: string | null; quality?: string; qualityVariants?: Record<string, string> | null; onActiveTime: (seconds: number) => void };

export function BroPlayer({ source, title, poster, quality = "1080p", qualityVariants, onActiveTime }: BroPlayerProps) {
  const video = useRef<HTMLVideoElement>(null); const gesture = useRef<{ side: "brightness" | "volume"; y: number; baseline: number } | null>(null); const lastTime = useRef<number | null>(null); const [playing, setPlaying] = useState(false); const [progress, setProgress] = useState(0); const [duration, setDuration] = useState(0); const [volume, setVolume] = useState(80); const [brightness, setBrightness] = useState(100); const [speed, setSpeed] = useState(1); const [qualityChoice, setQualityChoice] = useState("Auto"); const [indicator, setIndicator] = useState<{ type: "volume" | "brightness" | "seek"; value: string } | null>(null); const [showSettings, setShowSettings] = useState(false);
  const variants = useMemo<Record<string, string>>(() => ({ Auto: source, ...(qualityVariants ?? {}) }), [qualityVariants, source]); const activeSource = variants[qualityChoice] ?? source;
  const flash = (type: "volume" | "brightness" | "seek", value: string) => { setIndicator({ type, value }); window.setTimeout(() => setIndicator(null), 750); };
  const togglePlay = () => { const player = video.current; if (!player) return; if (player.paused) void player.play(); else player.pause(); };
  const seek = (amount: number) => { const player = video.current; if (!player) return; player.currentTime = Math.max(0, Math.min(player.duration || 0, player.currentTime + amount)); flash("seek", amount > 0 ? "+10s" : "−10s"); };
  const setPlayerVolume = (next: number) => { const value = Math.round(Math.min(100, Math.max(0, next))); setVolume(value); if (video.current) video.current.volume = value / 100; flash("volume", `${value}%`); };
  const pointerStart = (event: PointerEvent<HTMLDivElement>) => { const bounds = event.currentTarget.getBoundingClientRect(); const side = event.clientX - bounds.left < bounds.width / 2 ? "brightness" : "volume"; gesture.current = { side, y: event.clientY, baseline: side === "brightness" ? brightness : volume }; event.currentTarget.setPointerCapture(event.pointerId); };
  const pointerMove = (event: PointerEvent<HTMLDivElement>) => { if (!gesture.current) return; const rect = event.currentTarget.getBoundingClientRect(); const delta = ((gesture.current.y - event.clientY) / rect.height) * 120; const next = Math.round(Math.max(0, Math.min(100, gesture.current.baseline + delta))); if (gesture.current.side === "brightness") { setBrightness(next); flash("brightness", `${next}%`); } else setPlayerVolume(next); };
  const pointerEnd = () => { gesture.current = null; };
  useEffect(() => { if (video.current) video.current.playbackRate = speed; }, [speed]);
  useEffect(() => { setPlaying(false); setProgress(0); lastTime.current = null; }, [activeSource]);
  const onTimeUpdate = () => { const player = video.current; if (!player) return; setProgress(player.currentTime); if (player.paused || document.visibilityState !== "visible") { lastTime.current = player.currentTime; return; } if (lastTime.current !== null) onActiveTime(Math.max(0, Math.min(3, player.currentTime - lastTime.current))); lastTime.current = player.currentTime; };
  const indicatorIcon = indicator?.type === "brightness" ? <Sun className="h-7 w-7" /> : indicator?.type === "volume" ? <Volume2 className="h-7 w-7" /> : indicator?.value.startsWith("+") ? <RotateCw className="h-7 w-7" /> : <RotateCcw className="h-7 w-7" />;
  return <div className="relative aspect-video overflow-hidden rounded-[1.5rem] border border-white/[.09] bg-black shadow-2xl select-none" onPointerDown={pointerStart} onPointerMove={pointerMove} onPointerUp={pointerEnd} onPointerCancel={pointerEnd} onDoubleClick={event => { const rect = event.currentTarget.getBoundingClientRect(); seek(event.clientX - rect.left < rect.width / 2 ? -10 : 10); }}><video ref={video} src={activeSource} poster={poster ?? undefined} playsInline preload="metadata" onPlay={() => setPlaying(true)} onPause={() => setPlaying(false)} onTimeUpdate={onTimeUpdate} onLoadedMetadata={event => { setDuration(event.currentTarget.duration || 0); event.currentTarget.volume = volume / 100; }} onVolumeChange={event => { const value = Math.round(event.currentTarget.volume * 100); setVolume(value); flash("volume", `${value}%`); }} style={{ filter: `brightness(${Math.max(15, brightness)}%)` }} className="h-full w-full object-contain" />
    <div className="pointer-events-none absolute inset-0 bg-gradient-to-t from-black/90 via-transparent to-black/35" />
    {indicator && <div className="pointer-events-none absolute left-1/2 top-1/2 grid h-24 w-24 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-3xl border border-white/15 bg-black/70 text-white backdrop-blur"><div className="grid place-items-center gap-1">{indicatorIcon}<span className="text-sm font-black">{indicator.value}</span></div></div>}
    <div className="absolute left-4 top-4 flex items-center gap-2"><span className="rounded-lg bg-[#E50914] px-2.5 py-1 text-xs font-black tracking-[.12em] text-white">BRO PLAYER</span><span className="rounded-lg bg-black/60 px-2 py-1 text-xs font-bold text-zinc-300">{quality}</span></div>
    <button onClick={togglePlay} className="absolute left-1/2 top-1/2 grid h-16 w-16 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full bg-[#E50914] text-white shadow-[0_0_40px_rgba(229,9,20,.45)] transition hover:scale-105">{playing ? <Pause className="h-7 w-7 fill-current" /> : <Play className="ml-1 h-7 w-7 fill-current" />}</button>
    <div className="absolute bottom-0 left-0 right-0 p-4 sm:p-5"><p className="mb-3 truncate text-sm font-bold text-white">{title}</p><input aria-label="Seek video" type="range" min="0" max={duration || 0} step="0.1" value={progress} onChange={event => { if (video.current) video.current.currentTime = Number(event.target.value); }} className="bro-range w-full" /><div className="mt-3 flex items-center justify-between gap-2"><div className="flex items-center gap-1"><button onClick={() => seek(-10)} className="bro-control"><RotateCcw className="h-4 w-4" /></button><button onClick={togglePlay} className="bro-control">{playing ? <Pause className="h-4 w-4" /> : <Play className="h-4 w-4" />}</button><button onClick={() => seek(10)} className="bro-control"><RotateCw className="h-4 w-4" /></button><span className="ml-2 hidden text-xs font-medium text-zinc-300 sm:block">{formatTime(progress)} / {formatTime(duration)}</span></div><div className="flex items-center gap-1"><button onClick={() => setShowSettings(value => !value)} className="bro-control"><Settings2 className="h-4 w-4" /></button><button onClick={() => video.current?.requestFullscreen()} className="bro-control"><Expand className="h-4 w-4" /></button></div></div></div>
    {showSettings && <div className="absolute bottom-20 right-4 w-52 rounded-2xl border border-white/10 bg-zinc-950/95 p-3 text-sm shadow-2xl backdrop-blur"><label className="mb-3 block text-xs font-bold uppercase tracking-[.13em] text-zinc-500"><Gauge className="mr-1 inline h-3 w-3" />Speed<select value={speed} onChange={event => setSpeed(Number(event.target.value))} className="mt-1.5 w-full rounded-lg border border-white/10 bg-black px-2 py-2 text-sm text-white">{speeds.map(value => <option key={value} value={value}>{value}x</option>)}</select></label><label className="block text-xs font-bold uppercase tracking-[.13em] text-zinc-500">Quality<select value={qualityChoice} onChange={event => setQualityChoice(event.target.value)} className="mt-1.5 w-full rounded-lg border border-white/10 bg-black px-2 py-2 text-sm text-white">{qualityChoices.map(value => <option key={value} value={value} disabled={value !== "Auto" && !variants[value.replace(" HD", "")] && !variants[value]}>{value}</option>)}</select></label><p className="mt-3 text-[10px] leading-4 text-zinc-500">Swipe up/down on the left for brightness and on the right for volume. Double-tap either side to seek 10 seconds.</p></div>}
  </div>;
}
const formatTime = (seconds: number) => { if (!Number.isFinite(seconds)) return "0:00"; const mins = Math.floor(seconds / 60); return `${mins}:${String(Math.floor(seconds % 60)).padStart(2, "0")}`; };
